services:
  db:
    image: postgres:17-alpine
    container_name: habitjourney_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: habitjourney_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: