name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn -B clean verify
        env:
          JWT_SECRET: "dGVzdHNlY3JldGtleTEyMzQ1Njc4OTA="
          JWT_EXPIRATION: "86400000"

      - name: Generate Surefire Test Reports
        run: mvn surefire-report:report
        continue-on-error: true

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: target/site/
          if-no-files-found: warn

      - name: Upload Build Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: habitjourney-backend-jar
          path: target/*.jar
          if-no-files-found: warn